### ISSUE TITLE
ThuThesis 编译不通过

### ISSUE THREAD

**Issue by bigeagle** [CTeX-DEV/CTeX#18]
缺宏包，于是自动去下载，但是不少宏包无法正常自动安装，第一个出错的是 txfonts，手动装上，继续报错，错误原因都是 `xdvipdfmx:fatal: Unable to find TFM file "xxxxx".`

```
Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "main.tex"
Startup Folder: C:\Users\bigeagle\Desktop\texdemo\thuthesis

.....
======================================================================
starting package maintenance...
installation directory: C:\CTEX\UserData
package repository: http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/
lightweight database digest: 7c3c94a0e232fd23d69f7bc16d8118b6
going to download 126191 bytes
going to install 49 file(s) (1 package(s))
downloading http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/boondox.tar.lzma...
126191 bytes, 440.12 KB/Sec
extracting files from boondox.tar.lzma...

Unfortunately, the package boondox could not be installed.Please check the log file:
C:/CTEX/UserData/miktex/log/xdvipdfmx.log
======================================================================

xdvipdfmx:fatal: Unable to find TFM file "zxxrl7z".

Output file removed.
]
*************************************************
* fontspec warning: "script-not-exist"
* 
* Font 'YouYuan' does not contain script 'CJK'.
*************************************************
*************************************************
* fontspec warning: "script-not-exist"
* 
* Font 'LiSu' does not contain script 'CJK'.
*************************************************
(C:\CTEX\UserData\tex\latex\tex-gyre\t1qcr.fd)

LaTeX Warning: Reference `tab:template-files' on page 2 undefined on input line
 95.


LaTeX Warning: Reference `tab:tabexamp1' on page 2 undefined on input line 104.


[2
Sorry, but xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/CTEX/UserData/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.


_____________________________________________________________________

 XeLaTeX Compilation Report (Pages: 0)

 Errors: 0   Warnings: 11   Bad Boxes: 0
_____________________________________________________________________
```

**Comment by Harry-Chen** [comment]
装宏包出错还是第一次看到...
但是后面的表现像是缺字体一样

On Mon, Apr 18, 2016 at 11:22 PM, bigeagle < notifications@github.com [notifications@github.com] > wrote:
缺宏包，于是自动去下载，但是不少宏包无法正常自动安装，第一个出错的是 txfonts，手动装上，继续报错，错误原因都是 xdvipdfmx:fatal: Unable to find TFM file "xxxxx".

Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "main.tex"
Startup Folder: C:\Users\bigeagle\Desktop\texdemo\thuthesis

.....
======================================================================
starting package maintenance...
installation directory: C:\CTEX\UserData
package repository: http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/
lightweight database digest: 7c3c94a0e232fd23d69f7bc16d8118b6
going to download 126191 bytes
going to install 49 file(s) (1 package(s))
downloading http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/boondox.tar.lzma...
126191 bytes, 440.12 KB/Sec
extracting files from boondox.tar.lzma...

Unfortunately, the package boondox could not be installed.Please check the log file:
C:/CTEX/UserData/miktex/log/xdvipdfmx.log
======================================================================

xdvipdfmx:fatal: Unable to find TFM file "zxxrl7z".

Output file removed.
]
*************************************************
* fontspec warning: "script-not-exist"
* 
* Font 'YouYuan' does not contain script 'CJK'.
*************************************************
*************************************************
* fontspec warning: "script-not-exist"
* 
* Font 'LiSu' does not contain script 'CJK'.
*************************************************
(C:\CTEX\UserData\tex\latex\tex-gyre\t1qcr.fd)

LaTeX Warning: Reference `tab:template-files' on page 2 undefined on input line
 95.


LaTeX Warning: Reference `tab:tabexamp1' on page 2 undefined on input line 104.


[2
Sorry, but xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/CTEX/UserData/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.


_____________________________________________________________________

 XeLaTeX Compilation Report (Pages: 0)

 Errors: 0   Warnings: 11   Bad Boxes: 0
_____________________________________________________________________

**Comment by Harry-Chen** [comment]
然后这个zxxrl7z其实就是boondox宏包提供的🙈🙈🙈出错也不奇怪

On Mon, Apr 18, 2016 at 11:22 PM, bigeagle < notifications@github.com [notifications@github.com] > wrote:
缺宏包，于是自动去下载，但是不少宏包无法正常自动安装，第一个出错的是 txfonts，手动装上，继续报错，错误原因都是 xdvipdfmx:fatal: Unable to find TFM file "xxxxx".

Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "main.tex"
Startup Folder: C:\Users\bigeagle\Desktop\texdemo\thuthesis

.....
======================================================================
starting package maintenance...
installation directory: C:\CTEX\UserData
package repository: http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/
lightweight database digest: 7c3c94a0e232fd23d69f7bc16d8118b6
going to download 126191 bytes
going to install 49 file(s) (1 package(s))
downloading http://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/boondox.tar.lzma...
126191 bytes, 440.12 KB/Sec
extracting files from boondox.tar.lzma...

Unfortunately, the package boondox could not be installed.Please check the log file:
C:/CTEX/UserData/miktex/log/xdvipdfmx.log
======================================================================

xdvipdfmx:fatal: Unable to find TFM file "zxxrl7z".

Output file removed.
]
*************************************************
* fontspec warning: "script-not-exist"
* 
* Font 'YouYuan' does not contain script 'CJK'.
*************************************************
*************************************************
* fontspec warning: "script-not-exist"
* 
* Font 'LiSu' does not contain script 'CJK'.
*************************************************
(C:\CTEX\UserData\tex\latex\tex-gyre\t1qcr.fd)

LaTeX Warning: Reference `tab:template-files' on page 2 undefined on input line
 95.


LaTeX Warning: Reference `tab:tabexamp1' on page 2 undefined on input line 104.


[2
Sorry, but xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  C:/CTEX/UserData/miktex/log/xelatex.log

You may want to visit the MiKTeX project page, if you need help.


_____________________________________________________________________

 XeLaTeX Compilation Report (Pages: 0)

 Errors: 0   Warnings: 11   Bad Boxes: 0
_____________________________________________________________________

**Comment by Harry-Chen** [comment]
尝试复现中……

**Comment by MegaThomas** [comment]
继续手动装boondox就好了。接着还会报错，但只要找到

> Unfortunately, the package XXX could not be installed.Please check the log file:

然后手动装XXX宏包。多反复几次就OK了。

**Comment by ssydasheng** [comment]
Font 'YouYuan' does not contain script 'CJK'
Font 'LiSu' does not contain script 'CJK'

Same problem occurs to me, too. Have you solved this problem? 
@bigeagle

**Comment by bigeagle** [comment]
Nope. I'm not a CTeX user. I STRONGLY recommend everyone to switch to TeX Live. 
Developments of CTeX restarted in 2016.  Although CTeX developers are trying to push forward this project, due to the instability of MikTeX, which is almost abandoned by its maintainer. 

Therefore, 
I STRONGLY recommend everyone to switch to TeX Live, and 
I STRONGLY recommend everyone to switch to TeX Live, and
I STRONGLY recommend everyone to switch to TeX Live.

**Comment by ssydasheng** [comment]
:(, gg
