### ISSUE TITLE
更新path的时候全部覆盖

### ISSUE THREAD

**Issue by pobingwanghai** [CTeX-DEV/CTeX#19]

**Comment by bigeagle** [comment]
你tmd能把嘴洗干净再来说话吗

**Comment by pobingwanghai** [comment]
@bigeagle 我曹大哥，我错了，你能告诉我怎么把path回复吗，删我path等于烧我电脑啊，关键是我tmd道歉了你们能给我回复path吗我曹！！！！！！！！！！！！！！！！

**Comment by Liam0205** [comment]
「并不能」吗？那我是不是不该告诉你怎么找回？

首先，下载页面已经提醒过你了：
http://www.ctex.org/CTeXDownload

其次，这是打包工具的 bug，跟我们开发者没关系。

最后，在没重启的情况下，在注册表的 
```
HKEY_LOCAL_MACHINE\SYSTEM\ControlSet002\Control\Session Manager\Environment
```
可以找回。已经重启的话，就没办法了。

这个早已公开，轻易就能搜到。来这骂人是想被喷回去么？少年淡定点，没人喜欢你这幅样子。

**Comment by pobingwanghai** [comment]
由于我的不理智和冲动给各位带来的不快，表示非常非常的抱歉

**Comment by CHONSPQX** [comment]
然而我的电脑没有ControlSet002，怎么整？真的想说脏话。。。

**Comment by cetium** [comment]
CTeX_2.9.2.164还有这个bug，没仔细看说明已经中招了。熟悉这块的开发者赶紧想想办法吧
